protected/models/Product.php
<?php

/**
 * This is the model class for table "{{product}}".
 *
 * The followings are the available columns in table '{{product}}':
 * @property integer $id
 * @property integer $category_id
 * @property string $name
 * @property string $description
 * @property string $price
 * @property integer $sort
 *
 * The followings are the available model relations:
 * @property Foto[] $fotos
 * @property Order[] $orders
 * @property Category $category
 */
class Product extends CActiveRecord
{
	public function tableName()
	{
		return '{{product}}';
	}


	public function rules()
	{
		return array(
			array('category_id, name, description, price', 'required'),
			array('category_id, sort', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>128),
			array('price', 'length', 'max'=>10),
			array('id, category_id, name, description, price, sort', 'safe', 'on'=>'search'),
		);
	}


	public function relations()
	{
		return array(
			'fotos' => array(self::HAS_MANY, 'Foto', 'product_id'),
			'orders' => array(self::HAS_MANY, 'Order', 'product_id'),
			'category' => array(self::BELONGS_TO, 'Category', 'category_id'),
		);
	}


	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'category_id' => 'Category',
			'name' => 'Name',
			'description' => 'Description',
			'price' => 'Price',
			'sort' => 'Sort',
		);
	}


	public function search()
	{
		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('category_id',$this->category_id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('price',$this->price,true);
		$criteria->compare('sort',$this->sort);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}


	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}


	public function fotoProvider()
	{
		$criteria=new CDbCriteria;

		$criteria->compare('product_id', $this->id);

		return new CActiveDataProvider('Foto', ['criteria'=>$criteria]);
	}

}

protected/controllers/CategoryController.php
<?php

class CategoryController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Category;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Category']))
		{
			$model->attributes=$_POST['Category'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Category']))
		{
			$model->attributes=$_POST['Category'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Category');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Category the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Category::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Category $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='category-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/FotoController.php
<?php

class FotoController extends Controller
{

	public $layout='//layouts/column2';


	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}


	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete', 'add'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}


    public function actionUpdate($id=null, $product_id){
        // в зависимости от аргумента создаем модель или ищем уже существующую
        if($id==null){
            $model=new Foto();
        	$model->product_id=$product_id;
        }
        else if(!$model=Foto::model()->findByPk($id))
            throw new CHttpException(404,'The requested page does not exist.');

        if(isset($_POST['Foto'])){
            $model->attributes=$_POST['Foto'];
            if($model->save()){
            	$this->redirect(array('/product/view','id'=>$model->product_id));
            }
        }

        $this->render('update',array('model'=>$model));
        // $this->redirect(array('/product/view','id'=>$model->product_id));
    }


	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}


	public function loadModel($id)
	{
		$model=Foto::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}


	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='foto-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

}

protected/controllers/ProductController.php
<?php

class ProductController extends Controller
{

	public $layout='//layouts/column2';

	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'list'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}


	public function actionIndex($category_id)
	{
		$criteria=new CDbCriteria;
		$criteria->compare('category_id', $category_id);
		$dataProvider=new CActiveDataProvider('Product',
			['criteria'=>$criteria,
			'pagination'=>array('pageSize'=>false)
		]);

		$this->render('index',array(
				'dataProvider'=>$dataProvider,
				'category_id' => $category_id,
			));
	}


	public function actionView($id)
	{
		$this->render('view',array('model'=>$this->loadModel($id)));
	}


    public function actionUpdate($id=null, $category_id){
        // в зависимости от аргумента создаем модель или ищем уже существующую
        if($id == null){
            $model = new Product();
        	$model->category_id=$category_id;
        }
        else if( !$model=Product::model()->findByPk($id) )
            throw new CHttpException(404,'The requested page does not exist!!!');

        if(isset($_POST['Product'])){
            $model->attributes=$_POST['Product'];
            if($model->save()){
                $this->redirect(array('/product/view','id'=>$model->id));
            }
        }

        $this->render('update',array('model'=>$model));
    }


	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}


	public function actionAdmin()
	{
		$model=new Product('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Product']))
			$model->attributes=$_GET['Product'];

		$this->render('admin',array('model'=>$model,));
	}


	public function loadModel($id)
	{
		$model=Product::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}


	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='product-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/product/_form.php
<?php
/* @var $this ProductController */
/* @var $model Product */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'product-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'description'); ?>
		<?php echo $form->textArea($model,'description',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'description'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'price'); ?>
		<?php echo $form->textField($model,'price',array('size'=>10,'maxlength'=>10)); ?>
		<?php echo $form->error($model,'price'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'sort'); ?>
		<?php echo $form->textField($model,'sort'); ?>
		<?php echo $form->error($model,'sort'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/product/_search.php
<?php
/* @var $this ProductController */
/* @var $model Product */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'category_id'); ?>
		<?php echo $form->textField($model,'category_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'description'); ?>
		<?php echo $form->textArea($model,'description',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'price'); ?>
		<?php echo $form->textField($model,'price',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'sort'); ?>
		<?php echo $form->textField($model,'sort'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/product/_viewAdmin.php
<?php
/* @var $this ProductController */
/* @var $data Product */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::encode($data->id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('category_id')); ?>:</b>
	<?php echo CHtml::encode($data->category_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->name), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b>
	<?php echo CHtml::encode($data->description); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('price')); ?>:</b>
	<?php echo CHtml::encode($data->price); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('sort')); ?>:</b>
	<?php echo CHtml::encode($data->sort); ?>
	<br />

#добавить мини фото
</div>

protected/views/product/_viewUser.php
<?php
/* @var $this ProductController */
/* @var $data Product */
?>

	<h4><?php echo CHtml::encode($data->name); ?></h4>
<ul class="thumbnails">
	<?php foreach ($data->fotos as $foto) {
        echo '<li class="span2">';
		echo CHtml::link(CHtml::image("../../../images/$foto->img_path",
			'this is alt tag of image',
			 array(
				'style' => 'border:1px solid #eee; height:140px !important;',
			)
		),"../../../images/$foto->img_path",['data-lightbox'=>"$foto->img_path",]
		);
        echo '</li>';

    } ?>
</ul>

<div class="row">
    <div class="span2">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'label'=>'Заказать',
            'type'=>'primary',
            'htmlOptions'=>[
                'class'=>'input-block-level btn btn-info',
                'data-toggle'=>'modal',
                'data-target'=>"#product_modal_$data->id",
            ]
        )); ?>
    </div>
    <div class="span10">
        <?php echo CHtml::encode($data->description); ?>

        <b><?php echo CHtml::encode($data->getAttributeLabel('Цена')); ?>:</b>
        <?php echo CHtml::encode($data->price); ?>
    </div>

</div>


<hr>


<?php $this->beginWidget('bootstrap.widgets.TbModal', [
	'htmlOptions'=>[
		'id'=>"product_modal_$data->id"
	]
]); ?>

	<div class="modal-header">
	    <a class="close" data-dismiss="modal">&times;</a>
	    <h3>Заказ</h3>
	</div>
	<div class="modal-body">
		<?php $this->renderPartial('application.views.order._form',
			array('model'=>new Order, 'product_id'=>$data->id)
		); ?>
	</div>

	<div class="modal-footer">
	    <?php $this->widget('bootstrap.widgets.TbButton', array(
	        'label'=>'Зарыть',
	        'url'=>'#',
	        'htmlOptions'=>array('data-dismiss'=>'modal'),
	    )); ?>
	</div>

<?php $this->endWidget(); ?>

<?php if(Yii::app()->session['order']) :?>
<div id="1212" class="modal fade in">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
<!--         <h4 class="modal-title">Modal title</h4>
 -->      </div>
      <div class="modal-body">
        <p>Ваш заказ отправлен, вскоре мы с Вами свяжемся!!!&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="$('#1212').addClass('hide')">Close</button>
        <?php Yii::app()->session['order'] = false; ?>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<?php endif ?>

protected/views/product/admin.php
<?php
/* @var $this ProductController */
/* @var $model Product */

$this->breadcrumbs=array(
	'Products'=>array('index', 'category_id'=>$model->category_id),
	'Manage',
);

$this->menu=array(
	array('label'=>'Обзор продуктов',
			'url'=>array('index', 'category_id'=>$model->category_id),
	),
	array('label'=>'Создать Продукт',
			'url'=>array('update', 'id'=> null, 'category_id'=>$model->category_id),
			'visible'=>Yii::app()->user->name == 'admin'
	),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#product-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Products</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'product-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'category_id',
		'name',
		'description',
		'price',
		'sort',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/product/index.php
<?php
/* @var $this ProductController */
/* @var $dataProvider CActiveDataProvider */

$this->layout = '//layouts/column2';


$this->menu=array(
	array(	'label'=>'Обновить категорию',
			'url'=>array('/category/update', 'id'=>$category_id),
			'visible'=>Yii::app()->user->name == 'admin',
	),
	array(	'label'=>'Удалить категорию',
			'url'=>'#',
			'linkOptions'=>array(	'submit'=>array('/category/delete','id'=>$category_id),
									'confirm'=>'Are you sure you want to delete this item?',
							),
			'visible'=>Yii::app()->user->name == 'admin',
	),
	array(	'label'=>'Создать Продукт',
			'url'=>array('update', 'id'=> null, 'category_id'=>$category_id),
			'visible'=>Yii::app()->user->name == 'admin'
	),
	array(	'label'=>'Управление продуктами', 'url'=>array('admin'),
			'visible'=>Yii::app()->user->name == 'admin',
	),
);
?>
<div class="row">
    <div class="span12 goods">
    <?php
        if (Yii::app()->user->name == 'admin'){
            $this->widget('zii.widgets.CListView', array(
                'dataProvider'=>$dataProvider,
                'itemView'=>'_viewAdmin',
                'summaryText' => '',
            ));
        }else{
            $this->widget('zii.widgets.CListView', array(
                'dataProvider'=>$dataProvider,
                'itemView'=>'_viewUser',
                'summaryText' => '',
            ));
        }
     ?>
    </div>
</div>

protected/views/product/update.php
<?php
/* @var $this ProductController */
/* @var $model Product */

$this->breadcrumbs=array(
	'Products'=>array('index', 'category_id'=>$model->category_id),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'Обзор продуктов',
			'url'=>array('index', 'category_id'=>$model->category_id),
	),
	array('label'=>'Управление Продуктами',
		'url'=>array('admin'),
		'visible'=>Yii::app()->user->name == 'admin',
	),
);
?>

<h1>Update Product <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/product/view.php
<?php
/* @var $this ProductController */
/* @var $model Product */

// $Category=Category::model()->findByPk($category_id);
$this->breadcrumbs=array(
	'Products' => array('index', 'category_id'=>$model->category_id),
	$model->name,
);

$this->menu=array(
	array(	'label'=>'Обзор продуктов',
			'url'=>array('index', 'category_id'=>$model->category_id),
	),
	array(	'label'=>'Создать Продукт',
			'url'=>array('update', 'id'=> null, 'category_id'=>$model->category_id),
			'visible'=>Yii::app()->user->name == 'admin'
	),
	array(	'label'=>'Обновить Продукт',
			'url'=>array('update', 'id'=>$model->id, 'category_id'=>$model->category_id),
			'visible'=>Yii::app()->user->name == 'admin'
	),
	array(	'label'=>'Добавить фото',
			'url'=>array('/foto/update', 'product_id'=>$model->id, 'id'=>null),
			'visible'=>Yii::app()->user->name == 'admin'
	),
	array(	'label'=>'Удалить Продукт',
			'url'=>'#',
			'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),
								'confirm'=>'Are you sure you want to delete this item?',
							),
			'visible'=>Yii::app()->user->name == 'admin'
	),

		array('label'=>'Manage Product', 'url'=>array('admin')),
);
?>

<h1>View Product #<?php echo $model->id; ?></h1>

<?php if (Yii::app()->user->name == 'admin'){
	$this->widget('zii.widgets.CDetailView', array(
		'data'=>$model,
		'attributes'=>array(
			'id',
			'category_id',
			'name',
			'description',
			'price',
			'sort',
		)));
}else{
	$this->widget('zii.widgets.CDetailView', array(
		'data'=>$model,
		'attributes'=>array(
			'name',
			'description',
			'price',
		)));
}?>

<?php if (Yii::app()->user->name == 'admin'){
	$this->widget('zii.widgets.CListView', array(
		'dataProvider'=>$model->fotoProvider(),
		'itemView'=>'/foto/_viewAdmin',
	));
}else{
	$this->widget('zii.widgets.CListView', array(
		'dataProvider'=>$model->fotoProvider(),
		'itemView'=>'/foto/_viewUser',
	));
}?>